### ISSUE TITLE
Using @HANDLE instead of widget ID

### ISSUE THREAD

**Issue by zewt112** [userapp-io/twitter-timeline-angularjs#1]
Hi, love this code, thank you!

I wondered if you know a way that I can put in a twitter handle instead of a widget ID into the html twitter-timline tag? Using Angular, it would be good to be able to input twitter handles as expressions, eg twitter-timeline="{{ twitterHandle }}" instead of the widget ID to save from creating a new widget for every timeline one would want to display.

**Comment by timothyej** [comment]
Thank you, and sorry for the delay!

That would be a great feature, but unfortunately the Twitter widget doesn't allow that :(

**Comment by zewt112** [comment]
Ah, ok. Shame. Thanks for the code anyway!

On Sun, Feb 9, 2014 at 6:22 AM, Timothy E. Johansson <
notifications@github.com> wrote:

> Thank you, and sorry for the delay!
> 
> That would be a great feature, but unfortunately the Twitter widget
> doesn't allow that :(
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/userapp-io/twitter-timeline-angularjs/issues/1#issuecomment-34566759
> .

## 

George Wetz

_Unities_
+44 (0) 7825 779 606
unities.co.uk

**Comment by ghost** [comment]
@timothyej Look here: https://github.com/userapp-io/twitter-timeline-angularjs/pull/2
